// Package invoice provides a client for interacting with the MercadoPago Authorized Payments
// (Invoice) API.
//
// Invoices represent authorized payments generated by subscriptions. Each invoice corresponds
// to a billing cycle of a subscription and tracks the payment status, amount, retry attempts,
// and associated payment details. Use this package to retrieve individual invoices or search
// across invoices for a subscription.
//
// For more information, see the MercadoPago Subscriptions API reference:
// https://www.mercadopago.com/developers/en/reference/subscriptions/_authorized_payments_id/get
package invoice

import (
	"context"
	"net/http"

	"github.com/mercadopago/sdk-go/pkg/config"
	"github.com/mercadopago/sdk-go/pkg/internal/httpclient"
)

const (
	urlBase   = "https://api.mercadopago.com/authorized_payments"
	urlSearch = urlBase + "/search"
	urlWithID = urlBase + "/{id}"
)

// Client defines the interface for interacting with the MercadoPago Authorized Payments (Invoice) API.
// It provides methods to retrieve and search invoices associated with subscriptions.
type Client interface {
	// Get retrieves an invoice (authorized payment) by its unique identifier.
	//
	// It performs a GET request to: https://api.mercadopago.com/authorized_payments/{id}
	//
	// Reference: https://www.mercadopago.com/developers/en/reference/subscriptions/_authorized_payments_id/get
	Get(ctx context.Context, id string) (*Response, error)

	// Search finds invoices for subscriptions matching the filters specified in [SearchRequest].
	// Results are paginated and returned as a [SearchResponse].
	//
	// It performs a GET request to: https://api.mercadopago.com/authorized_payments/search
	//
	// Reference: https://www.mercadopago.com/developers/en/reference/subscriptions/_authorized_payments_search/get
	Search(ctx context.Context, request SearchRequest) (*SearchResponse, error)
}

// client is the unexported implementation of [Client].
type client struct {
	cfg *config.Config
}

// NewClient creates and returns a new Invoice (Authorized Payments) API [Client] configured
// with the provided [config.Config]. The config must contain a valid access token for
// authenticating requests to the MercadoPago API.
func NewClient(c *config.Config) Client {
	return &client{
		cfg: c,
	}
}

func (c *client) Get(ctx context.Context, id string) (*Response, error) {
	pathParams := map[string]string{
		"id": id,
	}

	requestData := httpclient.RequestData{
		Method:     http.MethodGet,
		URL:        urlWithID,
		PathParams: pathParams,
	}
	resource, err := httpclient.DoRequest[*Response](ctx, c.cfg, requestData)
	if err != nil {
		return nil, err
	}

	return resource, nil
}

func (c *client) Search(ctx context.Context, request SearchRequest) (*SearchResponse, error) {
	queryParams := request.GetParams()

	requestData := httpclient.RequestData{
		Method:      http.MethodGet,
		URL:         urlSearch,
		QueryParams: queryParams,
	}
	resource, err := httpclient.DoRequest[*SearchResponse](ctx, c.cfg, requestData)
	if err != nil {
		return nil, err
	}

	return resource, nil
}
