name: CD

on:
  release:
    types: [published]

jobs:
  release:
    name: Tag release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod

      - name: Verify module
        run: go build ./...

      - name: Run tests
        run: go test ./pkg/...
